import type { Advertiser } from "@/lib/ads";

/** Extra Holds in the network playlist. Original brands — not real companies. */
export const HOLD_CATALOG: Advertiser[] = [
  {
    id: "lumen-ward",
    name: "Lumen Ward",
    category: "Diagnostics",
    tagline: "Bloodwork by morning.",
    body: "A quiet draw. Results before the second coffee.",
    cta: "Book a draw",
    still: "/ads/lumen.jpg",
    video: "/ads/lumen-ward.mp4",
    holdMs: 8000,
    playable: {
      prompt: "What to run",
      options: [
        { id: "full", label: "Full panel", line: "The one your GP actually wanted.", wash: "rgba(180, 210, 200, 0.28)" },
        { id: "iron", label: "Iron", line: "Why the stairs feel longer.", wash: "rgba(140, 60, 50, 0.3)" },
        { id: "sugar", label: "Sugar", line: "A number, not a lecture.", wash: "rgba(210, 170, 80, 0.28)" },
        { id: "thyroid", label: "Thyroid", line: "The quiet one people skip.", wash: "rgba(80, 110, 140, 0.32)" },
      ],
    },
  },
  {
    id: "halo-cover",
    name: "Halo Cover",
    category: "Health cover",
    tagline: "The bill should not be the diagnosis.",
    body: "Hospital cover written in sentences a family can finish.",
    cta: "See plans",
    still: "/ads/halo-cover-hold.jpg",
    video: "/ads/halo-cover.mp4",
    holdMs: 8000,
  },
  {
    id: "quiet-room",
    name: "Quiet Room",
    category: "Mental health",
    tagline: "Forty minutes. A closed door.",
    body: "Talk therapy that starts this week, not next quarter.",
    cta: "Start tonight",
    still: "/ads/quietroom.jpg",
    video: "/ads/quiet-room.mp4",
    holdMs: 8000,
  },
  {
    id: "rivermist",
    name: "Rivermist",
    category: "Pharmacy",
    tagline: "Filled before you leave the chair.",
    body: "The script, the brand you asked for, a chemist who stays open.",
    cta: "Find a counter",
    still: "/ads/rivermist.jpg",
    video: "/ads/rivermist.mp4",
    holdMs: 8000,
  },
  {
    id: "pulse-line",
    name: "Pulse Line",
    category: "Telehealth",
    tagline: "A doctor in the language you think in.",
    body: "Video consults that do not begin with ‘can you hear me?’",
    cta: "Talk to a GP",
    still: "/ads/pulse-line-hold.jpg",
    video: "/ads/pulse-line.mp4",
    holdMs: 8000,
  },
  {
    id: "lantern-prep",
    name: "Lantern Prep",
    category: "Exam prep",
    tagline: "The paper is not a surprise.",
    body: "Past questions, a tutor who stays, a lamp that lasts the night.",
    cta: "Open a week",
    still: "/ads/lantern.jpg",
    video: "/ads/lantern-prep.mp4",
    holdMs: 8000,
  },
  {
    id: "amina-hall",
    name: "Amina Hall",
    category: "Lectures",
    tagline: "One subject. A teacher who stays.",
    body: "Recorded once. Explained until it sits.",
    cta: "Enrol",
    still: "/ads/amina.jpg",
    video: "/ads/amina-hall.mp4",
    holdMs: 8000,
  },
  {
    id: "ink-year",
    name: "Ink Year",
    category: "School",
    tagline: "A year that writes back.",
    body: "Small classes. Marked work that arrives before you forget the question.",
    cta: "Apply",
    still: "/ads/ink-year-hold.jpg",
    video: "/ads/ink-year.mp4",
    holdMs: 8000,
  },
  {
    id: "kasa-code",
    name: "Kasa Code",
    category: "Skills",
    tagline: "Ship something before the certificate.",
    body: "Twelve weeks. A product on a phone, not a slide.",
    cta: "Start a cohort",
    still: "/ads/threadcast.jpg",
    video: "/ads/kasa-code.mp4",
    holdMs: 8000,
  },
  {
    id: "threadcast",
    name: "Threadcast",
    category: "Cloud",
    tagline: "Your model, close to the people who wait on it.",
    body: "Inference in the city it serves. Less spinner. More answer.",
    cta: "Read the docs",
    still: "/ads/threadcast-hold.jpg",
    video: "/ads/threadcast.mp4",
    holdMs: 8000,
  },
  {
    id: "glassfield",
    name: "Glassfield",
    category: "Devices",
    tagline: "A phone that lasts a harmattan.",
    body: "Dust, heat, a battery that still has Thursday in it.",
    cta: "See the handset",
    still: "/ads/glassfield.jpg",
    video: "/ads/glassfield.mp4",
    holdMs: 8000,
  },
  {
    id: "redoubt",
    name: "Redoubt",
    category: "Security",
    tagline: "Lock the door you forgot you left open.",
    body: "One scan. The accounts still using last year’s password.",
    cta: "Run a scan",
    still: "/ads/redoubt.jpg",
    video: "/ads/redoubt.mp4",
    holdMs: 8000,
  },
  {
    id: "yaba-chip",
    name: "Yaba Chip",
    category: "Semiconductors",
    tagline: "Designed here. Soldered for this heat.",
    body: "Boards that do not quit at 38 degrees.",
    cta: "Meet the board",
    still: "/ads/yaba-chip-hold.jpg",
    video: "/ads/yaba-chip.mp4",
    holdMs: 8000,
  },
  {
    id: "lowcut",
    name: "Lowcut",
    category: "Listening",
    tagline: "The mix, not the algorithm.",
    body: "A listening app that still has albums.",
    cta: "Play the room",
    still: "/ads/harmattan.jpg",
    video: "/ads/lowcut.mp4",
    holdMs: 8000,
  },
  {
    id: "harmattan-records",
    name: "Harmattan Records",
    category: "Label",
    tagline: "First press. No skip on the A-side.",
    body: "Vinyl and files from rooms that still have a soundcheck.",
    cta: "Hear the EP",
    still: "/ads/harmattan-records-hold.jpg",
    video: "/ads/harmattan-records.mp4",
    holdMs: 8000,
  },
  {
    id: "night-yard",
    name: "Night Yard",
    category: "Live",
    tagline: "A yard that still has a soundcheck.",
    body: "Tables in the dust. A set that starts when it starts.",
    cta: "Get a table",
    still: "/ads/nightyard.jpg",
    video: "/ads/night-yard.mp4",
    holdMs: 8000,
    playable: {
      prompt: "Which door",
      options: [
        { id: "front", label: "Yard", line: "Laterite, lights, the first beer.", wash: "rgba(160, 90, 40, 0.32)" },
        { id: "back", label: "Back room", line: "The second set. Fewer phones.", wash: "rgba(40, 28, 24, 0.42)" },
        { id: "roof", label: "Roof", line: "The city, a little quieter.", wash: "rgba(70, 80, 110, 0.34)" },
        { id: "late", label: "After", line: "When the generator is the kick.", wash: "rgba(30, 30, 28, 0.45)" },
      ],
    },
  },
  {
    id: "second-voice",
    name: "Second Voice",
    category: "Artists",
    tagline: "The feature you actually wanted.",
    body: "A roster that still tours the rooms that built it.",
    cta: "Follow the drop",
    still: "/ads/second-voice-hold.jpg",
    video: "/ads/second-voice.mp4",
    holdMs: 8000,
  },
  {
    id: "reelhouse",
    name: "Reelhouse",
    category: "Cinema",
    tagline: "One screen. Then the title.",
    body: "A single-screen house. Seats that still face forward.",
    cta: "Book a seat",
    still: "/ads/reelhouse.jpg",
    video: "/ads/reelhouse.mp4",
    holdMs: 8000,
  },
  {
    id: "afterlight",
    name: "Afterlight",
    category: "Film",
    tagline: "Films that end. Not a feed.",
    body: "A catalogue with last pages. Watch one, go to bed.",
    cta: "Start a title",
    still: "/ads/afterlight-hold.jpg",
    video: "/ads/afterlight.mp4",
    holdMs: 8000,
  },
  {
    id: "harmattan-fest",
    name: "Harmattan Fest",
    category: "Festival",
    tagline: "Five days. No red carpet.",
    body: "Shorts, features, a queue that still talks after.",
    cta: "See the slate",
    still: "/ads/harmattan-fest-hold.jpg",
    video: "/ads/harmattan-fest.mp4",
    holdMs: 8000,
  },
  {
    id: "mangrove-homes",
    name: "Mangrove Homes",
    category: "Residences",
    tagline: "A house that knows the water.",
    body: "Stilt, timber, a lagoon that is the garden.",
    cta: "View a plot",
    still: "/ads/mangrove.jpg",
    video: "/ads/mangrove-homes.mp4",
    holdMs: 8000,
  },
  {
    id: "ikoyi-light",
    name: "Ikoyi Light",
    category: "Apartments",
    tagline: "High enough to see the lagoon work.",
    body: "A floor, a view, a rent that is written down.",
    cta: "Book a viewing",
    still: "/ads/ikoyi.jpg",
    video: "/ads/ikoyi-light.mp4",
    holdMs: 8000,
  },
  {
    id: "laterite-title",
    name: "Laterite",
    category: "Land",
    tagline: "Title first. Then the fence.",
    body: "Searched, surveyed, a deed you can hold.",
    cta: "Check a title",
    still: "/ads/laterite-land.jpg",
    video: "/ads/laterite-title.mp4",
    holdMs: 8000,
  },
  {
    id: "tenant-hour",
    name: "Tenant Hour",
    category: "Rentals",
    tagline: "The inspection is twenty minutes. Honest.",
    body: "Flats with photos of the actual wall.",
    cta: "See listings",
    still: "/ads/tenant-hour-hold.jpg",
    video: "/ads/tenant-hour.mp4",
    holdMs: 8000,
  },
  {
    id: "threadline",
    name: "Threadline",
    category: "Social",
    tagline: "Groups, not a stage.",
    body: "Rooms of people you would sit with. Phones face down.",
    cta: "Join a room",
    still: "/ads/threadline.jpg",
    video: "/ads/threadline.mp4",
    holdMs: 8000,
  },
  {
    id: "short-yard",
    name: "Short Yard",
    category: "Short video",
    tagline: "Fifteen seconds that belong to the maker.",
    body: "Cuts you can keep. Not a borrowed dance.",
    cta: "Post one",
    still: "/ads/short-yard-hold.jpg",
    video: "/ads/short-yard.mp4",
    holdMs: 8000,
  },
  {
    id: "circle-keep",
    name: "Circle Keep",
    category: "Community",
    tagline: "Twelve people. That’s the product.",
    body: "A small net. Dues. No strangers in the feed.",
    cta: "Open a circle",
    still: "/ads/circle-keep-hold.jpg",
    video: "/ads/circle-keep.mp4",
    holdMs: 8000,
  },
  {
    id: "cedar-book",
    name: "Cedar Book",
    category: "Funds",
    tagline: "A fund that writes in sentences.",
    body: "Holdings you can read. Fees on the first page.",
    cta: "Read the factsheet",
    still: "/ads/longrain.jpg",
    video: "/ads/cedar-book.mp4",
    holdMs: 8000,
  },
  {
    id: "long-rain",
    name: "Long Rain",
    category: "Pension",
    tagline: "Money that outlives the job.",
    body: "A pot that still has a letter with your name.",
    cta: "See the pot",
    still: "/ads/long-rain-hold.jpg",
    video: "/ads/long-rain.mp4",
    holdMs: 8000,
  },
  {
    id: "west-seed",
    name: "West Seed",
    category: "Venture",
    tagline: "Cheques for shops that already sell.",
    body: "First money after the till is real.",
    cta: "Pitch a round",
    still: "/ads/west-seed-hold.jpg",
    video: "/ads/west-seed.mp4",
    holdMs: 8000,
  },
  {
    id: "quiet-desk",
    name: "Quiet Desk",
    category: "Advisory",
    tagline: "Advice that fits on one page.",
    body: "An hour. A number. No deck with forty charts.",
    cta: "Book an hour",
    still: "/ads/current.jpg",
    video: "/ads/quiet-desk.mp4",
    holdMs: 8000,
  },
  {
    id: "current-house",
    name: "Current House",
    category: "Banking",
    tagline: "A current account that stays current.",
    body: "In, out, a balance you can say aloud.",
    cta: "Open one",
    still: "/ads/current-house-hold.jpg",
    video: "/ads/current-house.mp4",
    holdMs: 8000,
    playable: {
      prompt: "Open which book",
      options: [
        { id: "current", label: "Current", line: "The everyday till.", wash: "rgba(40, 70, 56, 0.38)" },
        { id: "save", label: "Save", line: "A pot with a lock you chose.", wash: "rgba(180, 150, 80, 0.28)" },
        { id: "usd", label: "Dollar", line: "For the invoice that isn’t naira.", wash: "rgba(70, 90, 70, 0.34)" },
        { id: "sme", label: "Shop", line: "Two signatories. One stamp.", wash: "rgba(90, 60, 40, 0.32)" },
      ],
    },
  },
  {
    id: "ledger-co",
    name: "Ledger & Co",
    category: "Cards",
    tagline: "One card. The rest is noise.",
    body: "Spend, a statement, a number that matches the till.",
    cta: "Request a card",
    still: "/ads/ledger-co-hold.jpg",
    video: "/ads/ledger-co.mp4",
    holdMs: 8000,
  },
  {
    id: "stall-credit",
    name: "Stall Credit",
    category: "SME",
    tagline: "Stock before the weekend market.",
    body: "A line that arrives while the goods are still on the road.",
    cta: "Get a line",
    still: "/ads/eveningpot.jpg",
    video: "/ads/stall-credit.mp4",
    holdMs: 8000,
  },
  {
    id: "crossing",
    name: "Crossing",
    category: "Diaspora",
    tagline: "Send it like you walked it over.",
    body: "A transfer that lands before the call ends.",
    cta: "Send today",
    still: "/ads/lagoonramp.jpg",
    video: "/ads/crossing.mp4",
    holdMs: 8000,
  },
  {
    id: "west-exchange",
    name: "West Exchange",
    category: "Markets",
    tagline: "The tape, without the shout.",
    body: "A board you can read. Hours that match this city.",
    cta: "Open a board",
    still: "/ads/nightmarket.jpg",
    video: "/ads/west-exchange.mp4",
    holdMs: 8000,
  },
  {
    id: "thin-spread",
    name: "Thin Spread",
    category: "Brokerage",
    tagline: "A kobo that stays a kobo.",
    body: "Orders that fill. Fees you can find.",
    cta: "Place a bid",
    still: "/ads/thin-spread-hold.jpg",
    video: "/ads/thin-spread.mp4",
    holdMs: 8000,
  },
  {
    id: "footnote",
    name: "Footnote",
    category: "Research",
    tagline: "The filing, not the rumour.",
    body: "Notes with sources. No rocket on the cover.",
    cta: "Read a note",
    still: "/ads/footnote-hold.jpg",
    video: "/ads/footnote.mp4",
    holdMs: 8000,
  },
  {
    id: "night-market",
    name: "Night Market",
    category: "Trading",
    tagline: "Hours when London is asleep.",
    body: "A book that stays open after the last bus.",
    cta: "Open a book",
    still: "/ads/night-market-hold.jpg",
    video: "/ads/night-market.mp4",
    holdMs: 8000,
  },
  {
    id: "grain-wire",
    name: "Grain Wire",
    category: "Commodities",
    tagline: "Cocoa, cashew, the price you were promised.",
    body: "Contracts that still name the port.",
    cta: "See contracts",
    still: "/ads/grain-wire-hold.jpg",
    video: "/ads/grain-wire.mp4",
    holdMs: 8000,
  },
  {
    id: "copy-desk",
    name: "Copy Desk",
    category: "Copy trade",
    tagline: "Follow a book, not a personality.",
    body: "A desk you can audit. Size you can cap.",
    cta: "Mirror a desk",
    still: "/ads/copy-desk-hold.jpg",
    video: "/ads/copy-desk.mp4",
    holdMs: 8000,
  },
  {
    id: "cedar-vault",
    name: "Cedar Vault",
    category: "Custody",
    tagline: "Keys you can name.",
    body: "Cold storage with a door, a log, a person.",
    cta: "Open a vault",
    still: "/ads/cedarvault.jpg",
    video: "/ads/cedar-vault.mp4",
    holdMs: 8000,
  },
  {
    id: "lagoon-ramp",
    name: "Lagoon Ramp",
    category: "On-ramp",
    tagline: "Naira in. Coin out. No theatre.",
    body: "A conversion you can explain to your father.",
    cta: "Convert",
    still: "/ads/lagoon-ramp-hold.jpg",
    video: "/ads/lagoon-ramp.mp4",
    holdMs: 8000,
  },
  {
    id: "quiet-chain",
    name: "Quiet Chain",
    category: "Wallet",
    tagline: "A wallet that does not ping.",
    body: "Send, receive, a seed you wrote down once.",
    cta: "Get the app",
    still: "/ads/quiet-chain-hold.jpg",
    video: "/ads/quiet-chain.mp4",
    holdMs: 8000,
  },
  {
    id: "block-hour",
    name: "Block Hour",
    category: "Exchange",
    tagline: "One pair. A spread you can see.",
    body: "A market with a clock, not a carnival.",
    cta: "Trade a pair",
    still: "/ads/block-hour-hold.jpg",
    video: "/ads/block-hour.mp4",
    holdMs: 8000,
  },
  {
    id: "dry-season",
    name: "Dry Season",
    category: "Data",
    tagline: "Data that lasts the month it sold.",
    body: "A plan with a number that does not evaporate on day nine.",
    cta: "Pick a plan",
    still: "/ads/dryseason.jpg",
    video: "/ads/dry-season.mp4",
    holdMs: 8000,
  },
  {
    id: "call-home",
    name: "Call Home",
    category: "Voice",
    tagline: "The call that still sounds like a room.",
    body: "Voice that does not fall apart at the greeting.",
    cta: "Dial",
    still: "/ads/call-home-hold.jpg",
    video: "/ads/call-home.mp4",
    holdMs: 8000,
  },
  {
    id: "roof-noon",
    name: "Roof Noon",
    category: "Solar",
    tagline: "The bill, cut at the roof.",
    body: "Panels, an inverter, a survey that shows the hours.",
    cta: "Get a survey",
    still: "/ads/roofnoon.jpg",
    video: "/ads/roof-noon.mp4",
    holdMs: 8000,
  },
  {
    id: "last-light",
    name: "Last Light",
    category: "Power",
    tagline: "Inverter hours you can count on.",
    body: "A pack that still has ten o’clock in it.",
    cta: "See a pack",
    still: "/ads/last-light-hold.jpg",
    video: "/ads/last-light.mp4",
    holdMs: 8000,
  },
  {
    id: "evening-pot",
    name: "Evening Pot",
    category: "Food",
    tagline: "The pot that still has a name.",
    body: "One soup. A rider who finds the gate.",
    cta: "Order tonight",
    still: "/ads/evening-pot-hold.jpg",
    video: "/ads/evening-pot.mp4",
    holdMs: 8000,
  },
  {
    id: "grain-loaf",
    name: "Grain Loaf",
    category: "Bakery",
    tagline: "Bread before the city wakes.",
    body: "Racks at four. Still warm at seven.",
    cta: "Find a shop",
    still: "/ads/grainloaf.jpg",
    video: "/ads/grain-loaf.mp4",
    holdMs: 8000,
  },
  {
    id: "laterite-pitch",
    name: "Laterite Pitch",
    category: "Football",
    tagline: "Boots, not a brand deal.",
    body: "A Saturday that still has a kick-off.",
    cta: "Get a ticket",
    still: "/ads/laterite.jpg",
    video: "/ads/laterite-pitch.mp4",
    holdMs: 8000,
  },
  {
    id: "dawn-split",
    name: "Dawn Split",
    category: "Fitness",
    tagline: "The 5:40 that actually happens.",
    body: "A pack, a coach, a floor that is already lit.",
    cta: "Join a pack",
    still: "/ads/dawnsplit.jpg",
    video: "/ads/dawn-split.mp4",
    holdMs: 8000,
  },
  {
    id: "mile-okada",
    name: "Mile",
    category: "Delivery",
    tagline: "There before the group chat argues.",
    body: "A parcel, a helmet, a gate that opens.",
    cta: "Send a parcel",
    still: "/ads/mile.jpg",
    video: "/ads/mile-okada.mp4",
    holdMs: 8000,
  },
  {
    id: "harmattan-cover",
    name: "Harmattan Cover",
    category: "Insurance",
    tagline: "Cover for the season that takes roofs.",
    body: "A claim that starts with a photo, not a queue.",
    cta: "Get a quote",
    still: "/ads/harmattancover.jpg",
    video: "/ads/harmattan-cover.mp4",
    holdMs: 8000,
  },
  {
    id: "ward-dawn",
    name: "Ward Dawn",
    category: "Hospital",
    tagline: "A ward that is already awake.",
    body: "Admissions before the traffic. A nurse who knows the file.",
    cta: "Book a bed",
    still: "/ads/warddawn.jpg",
    video: "/ads/ward-dawn.mp4",
    holdMs: 8000,
    playable: {
      prompt: "Which door",
      options: [
        { id: "gp", label: "GP", line: "The list you meant to make.", wash: "rgba(160, 190, 170, 0.28)" },
        { id: "lab", label: "Lab", line: "Drawn before the second coffee.", wash: "rgba(180, 210, 200, 0.28)" },
        { id: "scan", label: "Scan", line: "Same morning. Same floor.", wash: "rgba(80, 110, 140, 0.32)" },
        { id: "ward", label: "Ward", line: "A bed with a name on it.", wash: "rgba(40, 70, 56, 0.38)" },
      ],
    },
  },
  {
    id: "first-light",
    name: "First Light",
    category: "Maternity",
    tagline: "The first hour, not the first bill.",
    body: "A room, a midwife, a window that faces morning.",
    cta: "Tour a room",
    still: "/ads/firstlight.jpg",
    video: "/ads/first-light.mp4",
    holdMs: 8000,
  },
  {
    id: "ivory-chair",
    name: "Ivory Chair",
    category: "Dental",
    tagline: "The chair is forty minutes. Honest.",
    body: "A clean, a filling, a number you can say out loud.",
    cta: "Book a chair",
    still: "/ads/ivory-chair-hold.jpg",
    video: "/ads/ivory-chair.mp4",
    holdMs: 8000,
  },
  {
    id: "shore-shot",
    name: "Shore Shot",
    category: "Travel clinic",
    tagline: "The yellow card, before the gate.",
    body: "Jabs, a stamp, a nurse who has seen the form.",
    cta: "Get the card",
    still: "/ads/shore-shot-hold.jpg",
    video: "/ads/shore-shot.mp4",
    holdMs: 8000,
  },
  {
    id: "hall-desk",
    name: "Hall Desk",
    category: "University",
    tagline: "A seat that still faces the board.",
    body: "Lectures that start. Notes that arrive. A hall with a door.",
    cta: "Take a seat",
    still: "/ads/halldesk.jpg",
    video: "/ads/hall-desk.mp4",
    holdMs: 8000,
    playable: {
      prompt: "Which faculty",
      options: [
        { id: "law", label: "Law", line: "Cases, not slogans.", wash: "rgba(70, 50, 40, 0.36)" },
        { id: "med", label: "Medicine", line: "The ward after the hall.", wash: "rgba(160, 190, 170, 0.28)" },
        { id: "eng", label: "Engineering", line: "A workshop that is open.", wash: "rgba(80, 90, 100, 0.32)" },
        { id: "arts", label: "Arts", line: "A library that still has hours.", wash: "rgba(180, 150, 80, 0.28)" },
      ],
    },
  },
  {
    id: "second-tongue",
    name: "Second Tongue",
    category: "Language",
    tagline: "The language you need at the counter.",
    body: "French, Hausa, Yoruba, a tutor who stays the hour.",
    cta: "Book a tutor",
    still: "/ads/second-tongue-hold.jpg",
    video: "/ads/second-tongue.mp4",
    holdMs: 8000,
  },
  {
    id: "saturday-board",
    name: "Saturday Board",
    category: "Children",
    tagline: "A Saturday that still has a chalkboard.",
    body: "Small tables. Marked work. Home before the match.",
    cta: "Enrol a child",
    still: "/ads/saturday-board-hold.jpg",
    video: "/ads/saturday-board.mp4",
    holdMs: 8000,
  },
  {
    id: "merit-letter",
    name: "Merit Letter",
    category: "Scholarships",
    tagline: "The letter that pays the year.",
    body: "Forms that close. A committee that writes back.",
    cta: "Apply this round",
    still: "/ads/merit-letter-hold.jpg",
    video: "/ads/merit-letter.mp4",
    holdMs: 8000,
  },
  {
    id: "map-quiet",
    name: "Map Quiet",
    category: "Maps",
    tagline: "The road that is actually open.",
    body: "Traffic, gates, a pin that does not lie.",
    cta: "Open the map",
    still: "/ads/map-quiet-hold.jpg",
    video: "/ads/map-quiet.mp4",
    holdMs: 8000,
  },
  {
    id: "till-brick",
    name: "Till Brick",
    category: "Payments",
    tagline: "Tap. The till agrees.",
    body: "A brick, a receipt, a network that holds at noon.",
    cta: "Get a till",
    still: "/ads/till-brick-hold.jpg",
    video: "/ads/till-brick.mp4",
    holdMs: 8000,
  },
  {
    id: "orbit-lane",
    name: "Orbit Lane",
    category: "Satellite",
    tagline: "Internet that does not wait for the street.",
    body: "A dish, a plan, a line that works past the last mast.",
    cta: "See coverage",
    still: "/ads/orbit-lane-hold.jpg",
    video: "/ads/orbit-lane.mp4",
    holdMs: 8000,
  },
  {
    id: "sandbox-nine",
    name: "Sandbox Nine",
    category: "Developer tools",
    tagline: "Ship before the stand-up ends.",
    body: "A sandbox, logs, a deploy that does not need a priest.",
    cta: "Open a box",
    still: "/ads/sandbox-nine-hold.jpg",
    video: "/ads/sandbox-nine.mp4",
    holdMs: 8000,
  },
  {
    id: "soundcheck",
    name: "Soundcheck",
    category: "Studio",
    tagline: "The room is already quiet.",
    body: "A booth, an engineer, a take you can keep.",
    cta: "Book the room",
    still: "/ads/soundcheck.jpg",
    video: "/ads/soundcheck.mp4",
    holdMs: 8000,
    playable: {
      prompt: "How long",
      options: [
        { id: "hour", label: "An hour", line: "One vocal. Honest.", wash: "rgba(160, 90, 40, 0.32)" },
        { id: "night", label: "A night", line: "The mix after the city sleeps.", wash: "rgba(40, 28, 24, 0.42)" },
        { id: "week", label: "A week", line: "An EP that has a last song.", wash: "rgba(70, 80, 110, 0.34)" },
        { id: "live", label: "Live take", line: "No click. The room as it is.", wash: "rgba(30, 30, 28, 0.45)" },
      ],
    },
  },
  {
    id: "coast-fm",
    name: "Coast FM",
    category: "Radio",
    tagline: "The song, then the weather.",
    body: "A station that still has a presenter in the chair.",
    cta: "Tune in",
    still: "/ads/coast-fm-hold.jpg",
    video: "/ads/coast-fm.mp4",
    holdMs: 8000,
  },
  {
    id: "pressing-plant",
    name: "Pressing Plant",
    category: "Distribution",
    tagline: "The record leaves the plant.",
    body: "Pressing, sleeves, a van that finds the shops.",
    cta: "Press a run",
    still: "/ads/pressing-plant-hold.jpg",
    video: "/ads/pressing-plant.mp4",
    holdMs: 8000,
  },
  {
    id: "split-sheet",
    name: "Split Sheet",
    category: "Publishing",
    tagline: "The split, written down.",
    body: "Publishing that still has a percentage you can find.",
    cta: "Register a song",
    still: "/ads/split-sheet-hold.jpg",
    video: "/ads/split-sheet.mp4",
    holdMs: 8000,
  },
  {
    id: "night-reel",
    name: "Night Reel",
    category: "Streaming",
    tagline: "One film. Then sleep.",
    body: "A catalogue with endings. No next-episode trap.",
    cta: "Start a title",
    still: "/ads/night-reel-hold.jpg",
    video: "/ads/night-reel.mp4",
    holdMs: 8000,
  },
  {
    id: "call-sheet",
    name: "Call Sheet",
    category: "Production",
    tagline: "Call time is call time.",
    body: "Crew, locations, a producer who still has the list.",
    cta: "Crew a day",
    still: "/ads/call-sheet-hold.jpg",
    video: "/ads/call-sheet.mp4",
    holdMs: 8000,
  },
  {
    id: "subtitle-house",
    name: "Subtitle House",
    category: "Post",
    tagline: "The line, in the language of the room.",
    body: "Picture lock, subtitles, a mix that holds on a phone.",
    cta: "Book a pass",
    still: "/ads/subtitle-house-hold.jpg",
    video: "/ads/subtitle-house.mp4",
    holdMs: 8000,
  },
  {
    id: "blue-hour",
    name: "Blue Hour",
    category: "Open air",
    tagline: "A screen, a field, no carpet.",
    body: "One title. Chairs in the grass. The city a little quieter.",
    cta: "Get a chair",
    still: "/ads/blue-hour-hold.jpg",
    video: "/ads/blue-hour.mp4",
    holdMs: 8000,
  },
  {
    id: "estate-road",
    name: "Estate Road",
    category: "Estates",
    tagline: "The road is already in.",
    body: "Plots with lamps. A deed that is not a rumour.",
    cta: "Walk a plot",
    still: "/ads/estateroad.jpg",
    video: "/ads/estate-road.mp4",
    holdMs: 8000,
  },
  {
    id: "abuja-plot",
    name: "Abuja Plot",
    category: "Capital land",
    tagline: "Title in the city that files it.",
    body: "Surveyed, gazetted, a fence that can wait.",
    cta: "Check a file",
    still: "/ads/abuja-plot-hold.jpg",
    video: "/ads/abuja-plot.mp4",
    holdMs: 8000,
  },
  {
    id: "student-stair",
    name: "Student Stair",
    category: "Student housing",
    tagline: "A room near the hall. A lock that works.",
    body: "Beds, a cooker, rent that is written for the term.",
    cta: "See a room",
    still: "/ads/student-stair-hold.jpg",
    video: "/ads/student-stair.mp4",
    holdMs: 8000,
  },
  {
    id: "shop-front",
    name: "Shop Front",
    category: "Commercial",
    tagline: "A front that faces the foot.",
    body: "Ground floor. Meter in. A lease you can finish.",
    cta: "View a front",
    still: "/ads/shop-front-hold.jpg",
    video: "/ads/shop-front.mp4",
    holdMs: 8000,
  },
  {
    id: "face-down",
    name: "Face Down",
    category: "Dating",
    tagline: "Meet, then the phones go down.",
    body: "Profiles with a last name. A table, not a stage.",
    cta: "Make a table",
    still: "/ads/facedown.jpg",
    video: "/ads/face-down.mp4",
    holdMs: 8000,
    playable: {
      prompt: "What kind of table",
      options: [
        { id: "coffee", label: "Coffee", line: "Forty minutes. Daylight.", wash: "rgba(180, 150, 80, 0.28)" },
        { id: "walk", label: "A walk", line: "The marina, no menu.", wash: "rgba(120, 150, 164, 0.3)" },
        { id: "dinner", label: "Dinner", line: "One place. No scrolling.", wash: "rgba(90, 60, 40, 0.32)" },
        { id: "later", label: "Later", line: "When the city is quieter.", wash: "rgba(40, 28, 24, 0.42)" },
      ],
    },
  },
  {
    id: "morning-paper",
    name: "Morning Paper",
    category: "News",
    tagline: "The story, then the byline.",
    body: "A brief that still has a reporter attached.",
    cta: "Read the brief",
    still: "/ads/morning-paper-hold.jpg",
    video: "/ads/morning-paper.mp4",
    holdMs: 8000,
  },
  {
    id: "two-tick",
    name: "Two Tick",
    category: "Messaging",
    tagline: "Delivered. Not performed.",
    body: "Chats that stay in the chat. No public square.",
    cta: "Start a thread",
    still: "/ads/two-tick-hold.jpg",
    video: "/ads/two-tick.mp4",
    holdMs: 8000,
  },
  {
    id: "neighbour-gate",
    name: "Neighbour Gate",
    category: "Neighbourhood",
    tagline: "The street, not the internet.",
    body: "A gate group that still knows the generator man.",
    cta: "Join a street",
    still: "/ads/neighbour-gate-hold.jpg",
    video: "/ads/neighbour-gate.mp4",
    holdMs: 8000,
  },
  {
    id: "esusu-book",
    name: "Esusu Book",
    category: "Cooperative",
    tagline: "The pot, with a book.",
    body: "A contribution, a turn, a number the group can see.",
    cta: "Open a pot",
    still: "/ads/esusu-book-hold.jpg",
    video: "/ads/esusu-book.mp4",
    holdMs: 8000,
  },
  {
    id: "ninety-day",
    name: "Ninety Day",
    category: "Treasury",
    tagline: "Ninety days. The rate on the first line.",
    body: "Bills you can hold to the date. No story attached.",
    cta: "See this tenor",
    still: "/ads/ninety-day-hold.jpg",
    video: "/ads/ninety-day.mp4",
    holdMs: 8000,
  },
  {
    id: "compound-house",
    name: "Compound House",
    category: "REIT",
    tagline: "Rent, collected. Units, named.",
    body: "A fund of floors you can visit.",
    cta: "Read the units",
    still: "/ads/compound-house-hold.jpg",
    video: "/ads/compound-house.mp4",
    holdMs: 8000,
  },
  {
    id: "family-table",
    name: "Family Table",
    category: "Family office",
    tagline: "The table that outlives the founder.",
    body: "A will, a book, a meeting that still has minutes.",
    cta: "Sit the table",
    still: "/ads/family-table-hold.jpg",
    video: "/ads/family-table.mp4",
    holdMs: 8000,
  },
  {
    id: "quiet-branch",
    name: "Quiet Branch",
    category: "Private bank",
    tagline: "A branch with a door that closes.",
    body: "One banker. A number. Tea if you want it.",
    cta: "Request a desk",
    still: "/ads/quiet-branch-hold.jpg",
    video: "/ads/quiet-branch.mp4",
    holdMs: 8000,
    playable: {
      prompt: "What you need",
      options: [
        { id: "hold", label: "Hold", line: "Cash that stays cash.", wash: "rgba(40, 70, 56, 0.38)" },
        { id: "move", label: "Move", line: "A wire that lands today.", wash: "rgba(70, 90, 70, 0.34)" },
        { id: "next", label: "Next year", line: "A plan on one page.", wash: "rgba(180, 150, 80, 0.28)" },
        { id: "house", label: "House", line: "The deed, then the loan.", wash: "rgba(90, 60, 40, 0.32)" },
      ],
    },
  },
  {
    id: "market-till",
    name: "Market Till",
    category: "Microfinance",
    tagline: "Stock for the stall you already have.",
    body: "A small line. A collector who knows the market day.",
    cta: "Ask for a line",
    still: "/ads/market-till-hold.jpg",
    video: "/ads/market-till.mp4",
    holdMs: 8000,
  },
  {
    id: "crescent-book",
    name: "Crescent Book",
    category: "Islamic finance",
    tagline: "A book that does not charge the forbidden way.",
    body: "Trade, lease, a scholar who will sit with the contract.",
    cta: "Open a book",
    still: "/ads/crescent-book-hold.jpg",
    video: "/ads/crescent-book.mp4",
    holdMs: 8000,
  },
  {
    id: "night-counter",
    name: "Night Counter",
    category: "Digital bank",
    tagline: "The counter that does not close.",
    body: "Pay, save, a balance at 1 a.m. that is still the balance.",
    cta: "Open tonight",
    still: "/ads/night-counter-hold.jpg",
    video: "/ads/night-counter.mp4",
    holdMs: 8000,
  },
  {
    id: "tape-desk",
    name: "Tape Desk",
    category: "Stock market",
    tagline: "The tape, in this city’s hours.",
    body: "A board, a close, a print you can keep.",
    cta: "Open the tape",
    still: "/ads/tapedesk.jpg",
    video: "/ads/tape-desk.mp4",
    holdMs: 8000,
  },
  {
    id: "first-allotment",
    name: "First Allotment",
    category: "IPO",
    tagline: "The offer, the price, the allotment.",
    body: "A prospectus that still has a last page.",
    cta: "Read the offer",
    still: "/ads/first-allotment-hold.jpg",
    video: "/ads/first-allotment.mp4",
    holdMs: 8000,
  },
  {
    id: "index-ten",
    name: "Index Ten",
    category: "ETFs",
    tagline: "Ten names. One line.",
    body: "A fund that tracks the board, not a rumour.",
    cta: "Buy a unit",
    still: "/ads/index-ten-hold.jpg",
    video: "/ads/index-ten.mp4",
    holdMs: 8000,
  },
  {
    id: "dividend-day",
    name: "Dividend Day",
    category: "Equities",
    tagline: "The day the company pays you.",
    body: "Shares, a date, a credit that matches the notice.",
    cta: "See the calendar",
    still: "/ads/dividend-day-hold.jpg",
    video: "/ads/dividend-day.mp4",
    holdMs: 8000,
  },
  {
    id: "pair-desk",
    name: "Pair Desk",
    category: "Forex",
    tagline: "A pair. A spread you can see.",
    body: "Naira, dollar, a ticket that fills.",
    cta: "Trade a pair",
    still: "/ads/pair-desk-hold.jpg",
    video: "/ads/pair-desk.mp4",
    holdMs: 8000,
  },
  {
    id: "size-cap",
    name: "Size Cap",
    category: "Prop desk",
    tagline: "Size you can cap. A desk you can audit.",
    body: "A book with limits. No personality cult.",
    cta: "See the rules",
    still: "/ads/size-cap-hold.jpg",
    video: "/ads/size-cap.mp4",
    holdMs: 8000,
  },
  {
    id: "hedge-line",
    name: "Hedge Line",
    category: "Futures",
    tagline: "The hedge, not the bet.",
    body: "A contract that still names the month.",
    cta: "Open a month",
    still: "/ads/hedge-line-hold.jpg",
    video: "/ads/hedge-line.mp4",
    holdMs: 8000,
  },
  {
    id: "open-book",
    name: "Open Book",
    category: "Commodities",
    tagline: "The book stays open after the port closes.",
    body: "Cocoa, crude, a price with a clock.",
    cta: "Watch a contract",
    still: "/ads/cocoamat.jpg",
    video: "/ads/open-book.mp4",
    holdMs: 8000,
  },
  {
    id: "cold-hour",
    name: "Cold Hour",
    category: "Crypto OTC",
    tagline: "Size, off the carnival.",
    body: "A desk, a quote, settlement you can name.",
    cta: "Request a quote",
    still: "/ads/cold-hour-hold.jpg",
    video: "/ads/cold-hour.mp4",
    holdMs: 8000,
  },
  {
    id: "peg-desk",
    name: "Peg Desk",
    category: "Stablecoin",
    tagline: "A naira peg you can unwind.",
    body: "Payroll, invoices, a coin that is still a number.",
    cta: "Open a peg",
    still: "/ads/peg-desk-hold.jpg",
    video: "/ads/peg-desk.mp4",
    holdMs: 8000,
  },
  {
    id: "hash-quiet",
    name: "Hash Quiet",
    category: "Crypto infra",
    tagline: "The chain, without the carnival.",
    body: "Nodes, keys, an hour that is actually an hour.",
    cta: "Read the stack",
    still: "/ads/hash-quiet-hold.jpg",
    video: "/ads/hash-quiet.mp4",
    holdMs: 8000,
  },
  {
    id: "seed-paper",
    name: "Seed Paper",
    category: "Custody",
    tagline: "The words, on paper, once.",
    body: "A wallet whose seed you wrote down and put away.",
    cta: "Start a wallet",
    still: "/ads/seed-paper-hold.jpg",
    video: "/ads/seed-paper.mp4",
    holdMs: 8000,
  },
  {
    id: "chambers",
    name: "Chambers",
    category: "Legal",
    tagline: "The file, tied. The hour, billed.",
    body: "A chambers that still answers the letter.",
    cta: "Instruct a brief",
    still: "/ads/chambers.jpg",
    video: "/ads/chambers.mp4",
    holdMs: 8000,
  },
  {
    id: "chalk-cut",
    name: "Chalk Cut",
    category: "Fashion",
    tagline: "Chalk, shears, a coat that will last.",
    body: "Cut in a room with north light. Fitted once.",
    cta: "Book a fitting",
    still: "/ads/chalkcut.jpg",
    video: "/ads/chalk-cut.mp4",
    holdMs: 8000,
  },
  {
    id: "lagoon-room",
    name: "Lagoon Room",
    category: "Hotels",
    tagline: "A room that faces the water.",
    body: "Linen, a balcony, a night that does not need an itinerary.",
    cta: "Hold a night",
    still: "/ads/lagoonroom.jpg",
    video: "/ads/lagoon-room.mp4",
    holdMs: 8000,
  },
  {
    id: "wet-apron",
    name: "Wet Apron",
    category: "Aviation",
    tagline: "The stairs are already down.",
    body: "A regional hop. A cabin that still has a greeting.",
    cta: "See the hop",
    still: "/ads/wetapron.jpg",
    video: "/ads/wet-apron.mp4",
    holdMs: 8000,
  },
  {
    id: "cocoa-mat",
    name: "Cocoa Mat",
    category: "Agriculture",
    tagline: "Beans on the mat. Price on the page.",
    body: "A cooperative that still names the farmer.",
    cta: "Sell a bag",
    still: "/ads/cocoa-mat-hold.jpg",
    video: "/ads/cocoa-mat.mp4",
    holdMs: 8000,
  },
  {
    id: "ride-light",
    name: "Ride Light",
    category: "Mobility",
    tagline: "A car that is already on your street.",
    body: "A fare, a plate, a driver who finds the gate.",
    cta: "Call a car",
    still: "/ads/ride-light-hold.jpg",
    video: "/ads/ride-light.mp4",
    holdMs: 8000,
  },
  {
    id: "work-gate",
    name: "Work Gate",
    category: "Jobs",
    tagline: "The role, the pay, the gate.",
    body: "Listings with a salary. Interviews that happen.",
    cta: "See roles",
    still: "/ads/work-gate-hold.jpg",
    video: "/ads/work-gate.mp4",
    holdMs: 8000,
  },
];
