/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as BankRouteImport } from './routes/bank'
import { Route as FormatsRouteImport } from './routes/formats'
import { Route as HoldRouteImport } from './routes/hold'
import { Route as HolderRouteImport } from './routes/holder'
import { Route as InstallRouteImport } from './routes/install'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ProposalRouteImport } from './routes/proposal'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WaitsRouteImport } from './routes/waits'
import { Route as WatchAdIdRouteImport } from './routes/watch.$adId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatsRoute = FormatsRouteImport.update({
  id: '/formats',
  path: '/formats',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldRoute = HoldRouteImport.update({
  id: '/hold',
  path: '/hold',
  getParentRoute: () => rootRouteImport,
} as any)
const HolderRoute = HolderRouteImport.update({
  id: '/holder',
  path: '/holder',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitsRoute = WaitsRouteImport.update({
  id: '/waits',
  path: '/waits',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchAdIdRoute = WatchAdIdRouteImport.update({
  id: '/watch/$adId',
  path: '/watch/$adId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/bank': typeof BankRoute
  '/formats': typeof FormatsRoute
  '/hold': typeof HoldRoute
  '/holder': typeof HolderRoute
  '/install': typeof InstallRoute
  '/network': typeof NetworkRoute
  '/proposal': typeof ProposalRoute
  '/studio': typeof StudioRoute
  '/waits': typeof WaitsRoute
  '/watch/$adId': typeof WatchAdIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/bank': typeof BankRoute
  '/formats': typeof FormatsRoute
  '/hold': typeof HoldRoute
  '/holder': typeof HolderRoute
  '/install': typeof InstallRoute
  '/network': typeof NetworkRoute
  '/proposal': typeof ProposalRoute
  '/studio': typeof StudioRoute
  '/waits': typeof WaitsRoute
  '/watch/$adId': typeof WatchAdIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/bank': typeof BankRoute
  '/formats': typeof FormatsRoute
  '/hold': typeof HoldRoute
  '/holder': typeof HolderRoute
  '/install': typeof InstallRoute
  '/network': typeof NetworkRoute
  '/proposal': typeof ProposalRoute
  '/studio': typeof StudioRoute
  '/waits': typeof WaitsRoute
  '/watch/$adId': typeof WatchAdIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/bank'
    | '/formats'
    | '/hold'
    | '/holder'
    | '/install'
    | '/network'
    | '/proposal'
    | '/studio'
    | '/waits'
    | '/watch/$adId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/bank'
    | '/formats'
    | '/hold'
    | '/holder'
    | '/install'
    | '/network'
    | '/proposal'
    | '/studio'
    | '/waits'
    | '/watch/$adId'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/bank'
    | '/formats'
    | '/hold'
    | '/holder'
    | '/install'
    | '/network'
    | '/proposal'
    | '/studio'
    | '/waits'
    | '/watch/$adId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  BankRoute: typeof BankRoute
  FormatsRoute: typeof FormatsRoute
  HoldRoute: typeof HoldRoute
  HolderRoute: typeof HolderRoute
  InstallRoute: typeof InstallRoute
  NetworkRoute: typeof NetworkRoute
  ProposalRoute: typeof ProposalRoute
  StudioRoute: typeof StudioRoute
  WaitsRoute: typeof WaitsRoute
  WatchAdIdRoute: typeof WatchAdIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formats': {
      id: '/formats'
      path: '/formats'
      fullPath: '/formats'
      preLoaderRoute: typeof FormatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hold': {
      id: '/hold'
      path: '/hold'
      fullPath: '/hold'
      preLoaderRoute: typeof HoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holder': {
      id: '/holder'
      path: '/holder'
      fullPath: '/holder'
      preLoaderRoute: typeof HolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waits': {
      id: '/waits'
      path: '/waits'
      fullPath: '/waits'
      preLoaderRoute: typeof WaitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$adId': {
      id: '/watch/$adId'
      path: '/watch/$adId'
      fullPath: '/watch/$adId'
      preLoaderRoute: typeof WatchAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  BankRoute: BankRoute,
  FormatsRoute: FormatsRoute,
  HoldRoute: HoldRoute,
  HolderRoute: HolderRoute,
  InstallRoute: InstallRoute,
  NetworkRoute: NetworkRoute,
  ProposalRoute: ProposalRoute,
  StudioRoute: StudioRoute,
  WaitsRoute: WaitsRoute,
  WatchAdIdRoute: WatchAdIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
